```{r setup, include=FALSE}
cat("\014")
rm(list = ls())
```

```{r include=FALSE}
#recordar instalar los paquetes si no están instalados aún
library(ca)
library(FactoMineR)
library(factoextra)
library(ggplot2)
library(here)
```

```{r echo=TRUE}
#levando el mismo archivo usado en la clase 4
library(readxl)
datos_crudos=read_xlsx(here("labs", "lab8", "ds","montañas_rusas.xlsx"),sheet = 1)

datos_numericos_2 = data.frame(datos_crudos[c(1,8,9,10,12,13,15)])

#utilizo el filtro de complete cases de datos numericos sobre datos crudos
datos_completos_2 = datos_crudos[complete.cases(datos_numericos_2),]
#tengo 158, me quedo con este dataset para analizar
datos = datos_completos_2[c(7:10,12,13,15,16)]
```

```{r echo=TRUE}
# categorizacion de datos numericos
xs=quantile(datos$Height,seq(0,1,1/3))
datos$C_Height <- cut(datos$Height, breaks=xs,
                     labels=c("Height_low","Height_middle","Height_high"),
                     include.lowest = TRUE)

xs=quantile(datos$Speed,seq(0,1,1/3))
datos$C_Speed <- cut(datos$Speed , breaks=xs,
                     labels=c("Speed_slow","Speed_middle","Speed_fast"),
                     include.lowest = TRUE)

xs=quantile(datos$Length,seq(0,1,1/3))
datos$C_Length <- cut(datos$Length , breaks=xs,
                      labels=c("Length_short","Length_middle","Length_long"),
                      include.lowest = TRUE)

#para las inversiones el corte es por valor para separar
#las que no tienen inversiones estrictamente
xs=c(-Inf,0,4,Inf)
datos$C_Numinversions <- cut(datos$Numinversions , breaks=xs,
                             labels=c("Inv_none","Inv_few","Inv_lots"),
                             include.lowest = TRUE)

xs=quantile(datos$Duration,seq(0,1,1/3))
datos$C_Duration <- cut(datos$Duration , breaks=xs,
                        labels=c("Duration_short","Duration_middle","Duration_long"),
                        include.lowest = TRUE)

xs=c(-Inf,20,50,Inf)
datos$C_Age<- cut(2020-datos$Opened , breaks=xs,
                        labels=c("Age_new","Age_modern","Age_old"),
                        include.lowest = TRUE)

datos$C_Construction = as.factor(datos$Construction)
datos$C_Region = as.factor(datos$Region)

#observar el dataset obtenido y elegir variables para el acm
df_para_acm = datos[c(12,14,15,16)]

```

```{r echo=TRUE}
#otras variables categoricas
df.acm = MCA(df_para_acm , quali.sup=1 , graph=F)
summary(df.acm)
```

```{r echo=TRUE}
fviz_contrib(df.acm,choice="var",axes=1, fill="royalblue",color ="black")+
  theme_gray()

```

```{r echo=TRUE}
fviz_contrib(df.acm,choice="ind",axes=1, fill="royalblue",color ="black")+
theme_gray()

```

```{r echo=TRUE}
fviz_mca_var(df.acm,
             col.var="cos2" ,
             col.quali.sup = "black",
             gradient.cols = c("orange","red"),
             repel = TRUE)  + 
  theme_gray()

```
```{r echo=TRUE}
# fviz_mca_ind(df.acm , habillage = datos$C_Numinversions,addEllipses=TRUE, repel=TRUE,legend.title ="" ) +
# theme_gray ( ) +scale_color_brewer( palette="Paired" )

```



```{r echo=TRUE}

```

```{r echo=TRUE}

```

```{r echo=TRUE}

```

```{r echo=TRUE}

```
